### ISSUE TITLE
Connect doesn't work

### ISSUE THREAD

**Issue by colinfrei** [walty8/simple-gmail-notes.firefox-web-extension#1]
When I try connecting my Google Account, nothing happens.
I see the screen that says 'Choose an account from [G Suite Domain] to continue to Simple Gmail Notes'. When I click on the account, it highlights, but nothing else happens.

My guess is that it may have to do with the new google sign-in page.

I'm using Firefox Developer Edition, 54.0a2 (2017-04-18)

**Comment by colinfrei** [comment]
Just saw the note that this code isn't being maintained anymore... not sure what code exactly I'm running tbh, I installed the add-on from https://addons.mozilla.org/en-us/firefox/addon/simple-gmail-notes/, version 0.7.6a

**Comment by walty8** [comment]
hi, pls download the latest version from here:

https://www.bart.com.hk/sgn-releases/

I have submitted the new version for Firefox addon market review. It has been 4 weeks since the submission, and I am currently in the  middle of queue. I don't think the review would be done in short time.

**Comment by colinfrei** [comment]
seems to work great, thanks!
